apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-claim
  namespace: ha
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
