env:
  TZ: "America/New York"
ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      #kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.org/websocket-services: home-assistant
    hosts:
      - host: ha.rehl.xyz
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: ha-tls
        hosts:
          - ha.rehl.xyz
persistence:
  config:
    enabled: true
    existingClaim: ha-claim
