apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ha-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
