---
# Source: unifi/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-controller
  labels:
    app.kubernetes.io/name: unifi
    helm.sh/chart: unifi-0.6.4
    app.kubernetes.io/instance: unifi-controller
    app.kubernetes.io/managed-by: Helm
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
---

