---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10Gi"
