---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: unifi-claim
  namespace: unifi
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
