env:
  TZ: "America/New York"
ingress:
        #main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - unifi.rehl.xyz
    path: /
    tls:
      - secretName: unifi-tls
        hosts:
          - unifi.rehl.xyz
persistence:
  config:
    enabled: true
    existingClaim: unifi-claim
