apiVersion: v1
data:
  AMAVIS_LOGLEVEL: "0"
  DEFAULT_RELAY_HOST: ""
  DMS_DEBUG: "0"
  DOVECOT_AUTH_BIND: ""
  DOVECOT_MAILBOX_FORMAT: maildir
  DOVECOT_PASS_FILTER: ""
  DOVECOT_TLS: ""
  DOVECOT_USER_FILTER: ""
  ENABLE_AMAVIS: "1"
  ENABLE_CLAMAV: "0"
  ENABLE_FAIL2BAN: "0"
  ENABLE_FETCHMAIL: "0"
  ENABLE_LDAP: ""
  ENABLE_MANAGESIEVE: ""
  ENABLE_POP3: ""
  ENABLE_POSTFIX_VIRTUAL_TRANSPORT: ""
  ENABLE_POSTGREY: "0"
  ENABLE_QUOTAS: "1"
  ENABLE_SASLAUTHD: "0"
  ENABLE_SPAMASSASSIN: "0"
  ENABLE_SRS: "0"
  ENABLE_UPDATE_CHECK: "1"
  FAIL2BAN_BLOCKTYPE: drop
  FETCHMAIL_POLL: "300"
  LDAP_BIND_DN: ""
  LDAP_BIND_PW: ""
  LDAP_QUERY_FILTER_ALIAS: ""
  LDAP_QUERY_FILTER_DOMAIN: ""
  LDAP_QUERY_FILTER_GROUP: ""
  LDAP_QUERY_FILTER_USER: ""
  LDAP_SEARCH_BASE: ""
  LDAP_SERVER_HOST: ""
  LDAP_START_TLS: ""
  LOGWATCH_INTERVAL: ""
  LOGWATCH_RECIPIENT: ""
  MOVE_SPAM_TO_JUNK: "1"
  NETWORK_INTERFACE: ""
  ONE_DIR: "0"
  OVERRIDE_HOSTNAME: ""
  PERMIT_DOCKER: ""
  PFLOGSUMM_RECIPIENT: ""
  PFLOGSUMM_SENDER: ""
  PFLOGSUMM_TRIGGER: ""
  POSTFIX_DAGENT: ""
  POSTFIX_INET_PROTOCOLS: all
  POSTFIX_MAILBOX_SIZE_LIMIT: ""
  POSTFIX_MESSAGE_SIZE_LIMIT: ""
  POSTGREY_AUTO_WHITELIST_CLIENTS: "5"
  POSTGREY_DELAY: "300"
  POSTGREY_MAX_AGE: "35"
  POSTGREY_TEXT: Delayed by Postgrey
  POSTMASTER_ADDRESS: ""
  POSTSCREEN_ACTION: enforce
  RELAY_HOST: ""
  RELAY_PASSWORD: ""
  RELAY_PORT: "25"
  RELAY_USER: ""
  REPORT_INTERVAL: daily
  REPORT_RECIPIENT: "0"
  REPORT_SENDER: ""
  SA_KILL: "6.31"
  SA_SPAM_SUBJECT: '***SPAM*****'
  SA_TAG: "2.0"
  SA_TAG2: "6.31"
  SASL_PASSWD: ""
  SASLAUTHD_LDAP_AUTH_METHOD: ""
  SASLAUTHD_LDAP_BIND_DN: ""
  SASLAUTHD_LDAP_FILTER: ""
  SASLAUTHD_LDAP_MECH: ""
  SASLAUTHD_LDAP_PASSWORD: ""
  SASLAUTHD_LDAP_PASSWORD_ATTR: ""
  SASLAUTHD_LDAP_SEARCH_BASE: ""
  SASLAUTHD_LDAP_SERVER: ""
  SASLAUTHD_LDAP_START_TLS: ""
  SASLAUTHD_LDAP_TLS_CACERT_DIR: ""
  SASLAUTHD_LDAP_TLS_CACERT_FILE: ""
  SASLAUTHD_LDAP_TLS_CHECK_PEER: ""
  SASLAUTHD_MECH_OPTIONS: ""
  SASLAUTHD_MECHANISMS: ""
  SMTP_ONLY: ""
  SPAMASSASSIN_SPAM_TO_INBOX: "1"
  SPOOF_PROTECTION: ""
  SRS_EXCLUDE_DOMAINS: ""
  SRS_SECRET: ""
  SRS_SENDER_CLASSES: envelope_sender
  SSL_ALT_CERT_PATH: ""
  SSL_ALT_KEY_PATH: ""
  SSL_CERT_PATH: ""
  SSL_KEY_PATH: ""
  SSL_TYPE: ""
  SUPERVISOR_LOGLEVEL: ""
  TLS_LEVEL: ""
  UPDATE_CHECK_INTERVAL: 1d
  VIRUSMAILS_DELETE_DELAY: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mailserver-mailserver-env
  name: mailserver-env
  namespace: mail
