apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mailserver
  name: mailserver
spec:
  ports:
    - name: "25"
      port: 25
      targetPort: 25
    - name: "143"
      port: 143
      targetPort: 143
    - name: "465"
      port: 465
      targetPort: 465
    - name: "587"
      port: 587
      targetPort: 587
    - name: "993"
      port: 993
      targetPort: 993
  selector:
    io.kompose.service: mailserver
status:
  loadBalancer: {}
